[experiment]
name = "base_master_mix"
protocol = "base_mm.py"
parameters = "base_params.py"
sweep_calculator = "sweep_calculator.py"
csv = [
  "../experiment_setup/TEST/base_master_mix.csv",
  "../experiment_setup/TEST/reagents.csv",
  "../experiment_setup/TEST/samples_titration_labcraft.csv"
]
labware = "labware/"
verbose = true
artifacts_dir = "runs/"
